export const GET_REPORTS = "GET_REPORTS";
export const GET_REPORTS_SUCCESS = "GET_REPORTS_SUCCESS";
export const GET_REPORTS_ERROR = "GET_REPORTS_ERROR";

export const LOG_REPORT_SUCCESS = "LOG_REPORT_SUCCESS";
export const LOG_REPORT_ERROR = "LOG_REPORT_ERROR";
